'use strict';

const fs = require('fs');
const path = require('path');
const defaults = require('../../../config/defaults');
const bestModel = require('./best-model');

const bridge = {
  buildProviderConfig: (modelId, providerKeyName, baseUrl) => {
    return {
      id: modelId,
      name: modelId,
      auth: { api_key: `\${${providerKeyName}}` },
      base_url: baseUrl || null,
      transformer: {
        model: modelId,
        enhancetool: true,
        maxtoken: 16384
      }
    };
  },

  buildManifest: (models) => {
    if (!models.default) throw new Error('models.default required');
    
    return {
      version: '1.0.0',
      name: 'frugality-auto',
      description: 'Auto-generated by frugality bridge',
      Router: {
        default: models.default,
        background: models.background || models.default,
        think: models.think || models.default,
        longContext: models.longContext || models.default,
        longContextThreshold: 40000
      },
      Providers: Object.values(models).filter(Boolean).map(m => ({
        id: m.id,
        config: m.config
      }))
    };
  },

  writeManifest: (manifest, presetName, staging) => {
    try {
      if (!fs.existsSync(defaults.CCR_PRESETS_DIR)) {
        fs.mkdirSync(defaults.CCR_PRESETS_DIR, { recursive: true });
      }

      const dirName = staging ? `${presetName}-pending` : presetName;
      const presetDir = path.join(defaults.CCR_PRESETS_DIR, dirName);
      if (!fs.existsSync(presetDir)) {
        fs.mkdirSync(presetDir, { recursive: true });
      }

      const manifestFile = path.join(presetDir, 'manifest.json');
      const tempFile = manifestFile + '.tmp';
      fs.writeFileSync(tempFile, JSON.stringify(manifest, null, 2), 'utf8');
      fs.renameSync(tempFile, manifestFile);
      
      return presetDir;
    } catch (err) {
      throw new Error(`Failed to write manifest: ${err.message}`);
    }
  },

  promoteStaged: (presetName) => {
    try {
      const staged = path.join(defaults.CCR_PRESETS_DIR, `${presetName}-pending`);
      const active = path.join(defaults.CCR_PRESETS_DIR, presetName);

      if (!fs.existsSync(staged)) {
        throw new Error(`Staged preset not found: ${staged}`);
      }

      if (fs.existsSync(active)) {
        fs.rmSync(active, { recursive: true });
      }

      fs.renameSync(staged, active);
      return active;
    } catch (err) {
      throw new Error(`Failed to promote staged preset: ${err.message}`);
    }
  },

  runBridge: async (opts) => {
    try {
      opts = opts || {};
      const tier = opts.tier || defaults.MODEL_TIER;
      const dryRun = opts.dryRun || false;
      const immediate = opts.immediate !== false;
      
      const models = bestModel.queryFreeModels(tier);
      const defaultModel = bestModel.selectByTaskType(models, 'default');
      const bgModel = bestModel.selectByTaskType(models, 'fast');
      const thinkModel = bestModel.selectByTaskType(models, 'reasoning');
      const longModel = bestModel.selectByTaskType(models, 'analysis');

      if (!defaultModel) throw new Error('Could not select default model');

      const manifest = bridge.buildManifest({
        default: { id: defaultModel.modelId, config: {} },
        background: { id: bgModel.modelId, config: {} },
        think: { id: thinkModel.modelId, config: {} },
        longContext: { id: longModel.modelId, config: {} }
      });

      if (dryRun) {
        return { success: true, manifest, dryRun: true };
      }

      const presetDir = bridge.writeManifest(manifest, 'frugality-auto', !immediate);
      
      if (immediate) {
        bridge.promoteStaged('frugality-auto');
        fs.writeFileSync(defaults.PENDING_RESTART, JSON.stringify({
          reason: 'bridge update',
          timestamp: new Date().toISOString()
        }), 'utf8');
      } else {
        fs.writeFileSync(defaults.PENDING_CONFIG, JSON.stringify({
          preset: 'frugality-auto',
          timestamp: new Date().toISOString()
        }), 'utf8');
      }

      return { success: true, manifest, presetDir, staged: !immediate };
    } catch (err) {
      throw err;
    }
  }
};

module.exports = bridge;
